### ISSUE TITLE
TypeError: BpmnModdle is not a constructor

### ISSUE THREAD

**Issue by jackzhujie** [bpmn-io/bpmn-auto-layout#18] opened 2020-08-04 01:48 UTC
__Describe the Bug__

In our environment, after I used the bpmnModeler.connect() method to connect a line, I needed to automatically layout it, and I got an error: 
**BpmnModdle is not a constructor**

__Steps to Reproduce__

Example Code snippet

```js
const {xml} = await this.bpmnModeler.saveXML({format: true});
const autoLayout = new AutoLayout();
let layOutXml = await autoLayout(xml);`
```

Example [CodeSandbox](https://codesandbox.io/s/sqgt4?file=/src/index.js)

__Expected Behavior__

Should not crash.

**Comment by pinussilvestrus** [comment] 2020-08-04 13:23
For further assistance, please share a [CodeSandbox](https://codesandbox.io/s/bpmn-js-sandbox-3zkw0) that reproduces your issue in a way that we can inspect it.

**Comment by jackzhujie** [comment] 2020-08-05 01:13
[code](https://codesandbox.io/s/sqgt4?file=/src/index.js)

**Comment by pinussilvestrus** [comment] 2020-08-05 08:25
Thanks for sharing! Looks like an incompatibility with the latest `bpmn-moddle` version. We're open for a contribution which solves this issue 👍

**Comment by pinussilvestrus** [comment] 2020-08-06 08:12
Hint: the [AutoLayout module](https://github.com/bpmn-io/bpmn-auto-layout/blob/master/lib/AutoLayout.js#L15) should be updated to use the correct import statement for the BpmnModdle module.

```js
var BpmnModdle = require('bpmn-moddle').default;
```

**Comment by jackzhujie** [comment] 2020-08-06 08:14
> Hint: the [AutoLayout module](https://github.com/bpmn-io/bpmn-auto-layout/blob/master/lib/AutoLayout.js#L15) should be updated to use the correct import statement for the BpmnModdle module.
> 
> ```js
> var BpmnModdle = require('bpmn-moddle').default;
> ```

ok,thanks

**Comment by giero** [comment] 2020-11-13 10:16
Or switch to ES Modules syntax:
```javascript
import BpmnModdle from 'bpmn-moddle';
import Tree from './Tree';
import DiFactory from './DiFactory';

import DiUtil from './DiUtil';
```
and then
```javascript
export default AutoLayout;
```
This worked for me :) (got the sma bug btw)

**Comment by nikku** [comment] 2020-11-13 11:20
We are open to contributions that fix this.

**Comment by matiasah** [comment] 2021-01-12 22:24
> Hint: the [AutoLayout module](https://github.com/bpmn-io/bpmn-auto-layout/blob/master/lib/AutoLayout.js#L15) should be updated to use the correct import statement for the BpmnModdle module.
> 
> ```js
> var BpmnModdle = require('bpmn-moddle').default;
> ```

Would this definetly fix this issue? I'm also having this problem but I haven't tried this solution, I would open a PR with this if you confirm it works.

**Comment by nikku** [comment] 2021-01-12 23:23
> Would this definetly fix this issue?

You open the PR and find out :smile:

**Comment by matiasah** [comment] 2021-01-13 00:22
> Or switch to ES Modules syntax:
> 
> ```js
> import BpmnModdle from 'bpmn-moddle';
> import Tree from './Tree';
> import DiFactory from './DiFactory';
> 
> import DiUtil from './DiUtil';
> ```
> 
> and then
> 
> ```js
> export default AutoLayout;
> ```
> 
> This worked for me :) (got the sma bug btw)

I guess I'm going to try this instead

**Comment by nikku** [comment] 2021-01-13 12:13
Closing this issue as we do not plan to follow up on this one, unless we receive an external contribution (`pr-needed`).

**Closed** 2021-01-26 18:16 UTC
Labels: bug, pr-needed
